comment:
  layout: "reach, diff, flags, files, header, footer, feedback"
  behavior: default
github_checks: false

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: front1app  # this is an identifier that should not be changed
      name: Frontend Web  # this is a display name, and can be changed freely
      paths:
        - apps/front1/**
        - libs/lib2/**
    - component_id: backend1app
      name: The backend
      paths:
        - apps/back1/**
        - libs/lib1/**
        - libs/lib2/**
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
